### PR TITLE
Release v1.8.0

### PR DESCRIPTION
**Pull request by dbrakenhoff**
- Add parallel_solve for ArcticDB
- Improve searching in pastastore
- Parallel get statistics
- Parallel apply, and support returning results and converting to DataFrame/Series.

### CODE REVIEW

**Review by martinvonk — APPROVED** [review]

**Comment by dbrakenhoff** [comment]
Harsh, .01% off the coverage variation target :P

**Review by martinvonk — DISMISSED** [review]
Tested this a bit now and looks good for a new release.

**Review by martinvonk — APPROVED** [review]

**Review by martinvonk — APPROVED** [review]

**Comment by martinvonk** [comment]
Every time a commit happens my review with approval is dismissed but once and for all:
approve

**Comment by dbrakenhoff** [comment]
okokok, i will merge

**Pull request merged**
